name = "my-blog"
type = "javascript"

account_id = "your-account-id"
workers_dev = true
compatibility_date = "2024-10-03"

main_module = "_worker.js"

kv_namespaces = [
  { binding = "MY_KV_NAMESPACE", id = {env = "KV_ID"}} # 使用环境变量
]
